### ISSUE TITLE
Module doesn't have description specified

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-module-catalog-personalization#10]
Also need to remove "Virto Commerce" from authors.

![image](https://user-images.githubusercontent.com/1566470/32019750-0bb9bb18-b983-11e7-84ce-8801a0588c34.png)

**Comment by megafreeman** [comment]
Fixed in commit https://github.com/VirtoCommerce/vc-module-catalog-personalization/commit/9d806ba585e48a318027b197ce18e56137a6d59f

**Comment by yecli** [comment]
Released long time ago in [v1.0.1](https://github.com/VirtoCommerce/vc-module-catalog-personalization/releases/tag/v1.0.1).
