### ISSUE TITLE
Export of Personalisation modules fails

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-module-catalog-personalization#13]
![image](https://user-images.githubusercontent.com/5917756/41245599-1dc023a0-6db1-11e8-88b6-25fddaa91312.png)

**Comment by yecli** [comment]
@IgorisB Checked on the admin demo, seems it is OK now.
![image](https://user-images.githubusercontent.com/15610352/63768411-938df500-c8e9-11e9-9ecc-cfb52731e7db.png)
