### ISSUE TITLE
Category indexed search does not respect CategorySearchCriteria.UserGroups property

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-module-catalog-personalization#16]
When we are specifying `CategorySearchCriteria.UserGroups` for indexed search, it is not taken into consideration. In below "/api/catalog/search/categories" POST example all categories are returned:
```
{
    "skip": 0,
    "take": 15,
    "userGroups": ["VIP"]
}
```
But if we specify proper "user_groups" term, filtration performs properly - only "VIP" categories returned (if any).
```
{
    "skip": 0,
    "take": 15,
    "terms": ["user_groups:VIP"]
}
```
Seems we are missing adding proper term filter for UserGroups when searching categories. Need to add it (similar to [product search](https://github.com/VirtoCommerce/vc-module-catalog-personalization/blob/6348075bb6713cceef488222a8b928c2c0ced588/VirtoCommerce.CatalogPersonalizationModule.Data/Search/ProductSearchUserGroupsRequestBuilder.cs)).

UPD:
Also need take into account this requirement:
The customer may have a category that contains all products that are restricted while they may also have a category that has some products that are restricted.  We would expect a category that is ALL restricted to not be returned in a search while the category that only contains some restricted items would be returned.  A category with no restrictions would always return.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog-personalization/releases/tag/v1.1.0
