### ISSUE TITLE
UpTree propagation policy works incorrectly when category have tagged variations

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-module-catalog-personalization#23]
When we have 2 items in category, 1 with 1 variation (both tagged), __any group won't be propagated.
Probably tags in variations appeared when DownTree policy were applied.

**Solution**: Need to set SearchInVariations = true and WithHidden = true [here](https://github.com/VirtoCommerce/vc-module-catalog-personalization/blob/dev/VirtoCommerce.CatalogPersonalizationModule.Data/Services/Policies/UpTreeTagPropagationPolicy.cs#L74)

**Comment by ajestrab** [comment]
Another thing we noticed is that the Tags that are propagating up do not show listed as a tag on the entity.

**Comment by yecli** [comment]
@ajestrab we could add read only "inherited" tag list to tags blade and display "effective" tags count (manually added + inherited).
Is it what you need?

**Comment by ajestrab** [comment]
I think it would only make sense from a user experience perspective.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yecli** [comment]
Propagation policy is the logic for getting "effective" tags based on the related entities "user defined" tags. 
I think it should not assign tags the same way as user can do it manually.

Am I getting right you want these "effective" tags to be saved as the "user defined" ones? If so, what is the purpose of this?

**Comment by ajestrab** [comment]
No, not save just is strange they are not "Seen" without looking at the index.  it is fine how it works today.

**Comment by yecli** [comment]
Release with the bug fix:
https://github.com/VirtoCommerce/vc-module-catalog-personalization/releases/tag/v1.1.3
If we'll make UI changes, it'll be different issue.
