### ISSUE TITLE
Build main menu bar according to available categories

### ISSUE THREAD

**Issue by megafreeman** [VirtoCommerce/vc-module-catalog-personalization#7]

**Comment by megafreeman** [comment]
Need to change MenuLinkListServiceImpl service (https://github.com/VirtoCommerce/vc-storefront/blob/master/VirtoCommerce.Storefront/Services/LinkListServiceImpl.cs#L24) to populate categories and products via search methods instead of receiving by ids.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
