### ISSUE TITLE
When customer is assigned a tag no products are shown on storefront

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-module-catalog-personalization#9]
Assigning a group to a customer shouldn't automatically hide all the products from him. If products/categories/catalogs don't have any tags assigned to them, they should be visible to any customer regardless of groups he/she belongs to.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog-personalization/releases/tag/v1.0.1
